Written doc install-porter-en.
kubesphere/porter pull request #141
Opened 2021-01-25 06:41 UTC by Patrick-LuoYu

Signed-off-by: Patrick-LuoYu <patrickluo@yunify.com>
/assign @FeynmanZhou @zheng1 @duanjiong

2021-01-25 08:00 UTC, FeynmanZhou requested changes

2021-01-25 08:06 UTC, duanjiong commented on doc/install-porter.md
> +## Install Porter Using Helm Charts
I would recommend using helm3, but I have never used helm2 before. The current kubesphere installation is also helm3.

2021-01-25 08:09 UTC, FeynmanZhou commented on doc/install-porter.md
> +## Install Porter Using Helm Charts
There should be two installation guides: 
- Installing Porter on Kubernetes (Kubectl and Helm)
- Installing Porter on KubeSphere (Web Console)

2021-01-26 02:39 UTC, FeynmanZhou commented on doc/install-porter-on-kubernetes.md
> +```
@duanjiong Is it better to add the verification at the end of this guide? Users may not know whether the Porter is running normally or not.

2021-01-26 02:40 UTC, FeynmanZhou commented on doc/install-porter-on-kubesphere.md
> +   ![install-porter-1](./img/install-porter-8.jpg)
@duanjiong Same here.

2021-01-26 07:03 UTC, FeynmanZhou commented
I just noticed that all images are named with the serial number, I assume the images should be named with their related meaning. Do we need to add a rule for image naming in [Style Guide](https://github.com/kubesphere/website/blob/master/KubeSphere%20Documentation%20Style%20Guide.md#images)? @Sherlock113

2021-01-26 07:36 UTC, Patrick-LuoYu commented
I think naming images with numbers is better, because those images are usually only related to the document. I cannot come up with a scenario where image names with actual meanings could be useful. On the other hand, names with actual meanings make document writing and localization difficult because the images are difficult to locate when there are a huge number of images. Naming images with chapter numbers (which we don't have) and sequence numbers is a common practice in document writing.

2021-01-26 13:38 UTC, zheng1 commented
Please fix the conflict file

2021-01-27 01:58 UTC, closed without merging

2021-01-27 02:02 UTC, duanjiong commented
You can overwrite mine directly in English, and I'll write Chinese at the back